version: "0.5"
log_level: debug
log_length: 3000
processes:
  process0:
    command: "ls ddd"

  process1:
    command: "./test_loop.bash ${PROC4}"
    availability:
      restart: "on-failure"
      backoff_seconds: 2
    depends_on:
      _process2:
        condition: process_completed_successfully
      process3:
        condition: process_completed
      # process4:
      #   condition: process_completed_successfully
    environment:
      - 'EXIT_CODE=0'
    shutdown:
      command: "sleep 2 && pkill -f process1"
      signal: 15
      timeout_seconds: 4

  _process2:
    command: "./test_loop.bash process2"
    log_location: ./pc.proc2.log
    availability:
      restart: "on-failure"
    # depends_on:
    #   process3:
    #     condition: process_completed_successfully
    environment:
      - 'ABC=2221'
      - 'PRINT_ERR=111'
      - 'EXIT_CODE=2'
    shutdown:
      command: "sleep 2 && pkill -f process2"
      signal: 15
      timeout_seconds: 4

  process3:
    command: "./test_loop.bash process3"
    availability:
      restart: "on-failure"
      backoff_seconds: 2
    depends_on:
      process4:
        condition: process_completed_successfully

  process4:
    command: "./test_loop.bash process4"
    # availability:
    #   restart: on-failure
    environment:
      - 'ABC=2221'
      - 'EXIT_CODE=4'

  docker:
    command: "docker run -d --rm --name nginx_test nginx"
    # availability:
    #   restart: on-failure
    is_daemon: true
    shutdown:
      command: "docker stop nginx_test"
      signal: 15
      timeout_seconds: 5

  kcalc:
    command: "kcalc"
    disabled: true

environment:
  - 'ABC=222'
log_location: ./pc.log
